### PR TITLE
Licencing and Contrubution

### PR DESCRIPTION
**Pull request by stylesuxx**

### CODE REVIEW

**Comment by stylesuxx** [comment]
@j005u I am not sure how we should handle packages that change their licensing after the fact. I added a section about us forking the repo (and setting it to private) just in case - you think that I am being to paranoid here?

**Comment by j005u** [comment]
@stylesuxx I think that whole paragraph is unnecessary.

An OS license requirement in and of itself implies if you abandon your package in one way or another we could fork and re-publish it.

Our current build system is unusual in the way it grabs binaries from GH repos. If/when we port to entware we'd pull each repos source, build and package it in a central job anyway and would therefor always have the opportunity to archive the latest published source.

**Comment by stylesuxx** [comment]
> An OS license requirement in and of itself implies if you abandon your package in one way or another we could fork and re-publish it.

Yes, I am aware. I was just thinking about the case if the author pulls the repo completely. If we don't have a fork, then we also don't have any base from which we can publish. But you are right, if we build from source, we don't have this problem. You think I should remove the section about forking?

I would take the contribution "guidelines" from here and apply them on other repos, extending them where it makes sense - so yeah, if you could give it a short review and add your remarks, I will adjust accordingly.

I will also add a Discord link.

TODOs:
* [ ] Discord link

**Comment by j005u** [comment]
> Yes, I am aware. I was just thinking about the case if the author pulls the repo completely. If we don't have a fork, then we also don't have any base from which we can publish. But you are right, if we build from source, we don't have this problem. You think I should remove the section about forking?

I just don't think we need to state the obvious thing we can do if it's OS. And technically we could also do it as part of the repo build process and archive the source commit that any binaries were related to. It doesn't specifically have to be a private clone.

How we do it exactly technically doesn't matter in terms of contribution rules. Discussion TBC for our own archival purposes I think.

**Comment by j005u** [comment]
@stylesuxx I made tiny working changes and re-ordered a few things in a way that made more sense to me.
Feel free to revert if you disagree. Otherwise go ahead and merge?

**Pull request merged**
